#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
 TCR beta-Chain Repertoire Analysis Pipeline  (PYTHON, full)
 Breast Cancer  -  Treg vs CD4_Memory vs Other (CD45RA+)  -  BioProject PRJNA301507
================================================================================

 Companion code for:
   "Power-Law Modelling Reveals Regulatory T-Cell Clonal Dominance Undetected by
    Classical Diversity Metrics in Breast Cancer TCR beta-Chain Repertoires"

 This single script reproduces the ENTIRE analysis (old + strengthening):
   1  Load raw clonotype files + sample metadata
   2  Quality control & clonotype standardisation
   3  Alpha diversity (Shannon, inv. Simpson, Gini, Pielou, clonality,
      Hill q=0/1/2, Chao1, top-10% fraction)
   4  Beta diversity (Bray-Curtis, PCoA, PERMANOVA, dispersion, Morisita-Horn)
   5  Power-law modelling (pooled + PATIENT-LEVEL fixed x_min [primary];
      Clauset KS x_min; Vuong-style LR vs log-normal / exponential /
      truncated power law; bootstrap GOF; x_min sensitivity)
   6  Inter-patient clonal-sharing network (Jaccard, Louvain communities,
      Treg top-clone dominance, Kruskal-Wallis + epsilon^2)
   7  Linear mixed-effects model + ICC (+ cluster-bootstrap 95% CI)
   8  Degree centrality vs power-law alpha (Spearman)
   9  PERMANOVA post-hoc power analysis
  10  STRENGTHENING analyses:
      S1 metric-discrimination benchmark (Cohen's d + AUC)
      S2 truncated power-law model selection
      S3 community-detection robustness (Leiden/Walktrap/Infomap vs Louvain, ARI)
      S4 rarefaction-to-equal-depth alpha
      S5 bootstrap ICC CI (computed in stage 7)
  11  Figures (PNG) + all result tables (CSV)

 USAGE
   - Set DATA_DIR below to your data folder (default: D:\\PRJNA301507\\data).
   - Provide a sample metadata file (see SAMPLE METADATA section). If none is
     found the script tries to auto-build one and will tell you what to fix.
   - Run:   python tcr_analysis_pipeline.py
   - Outputs go to <DATA_DIR>\\..\\results  and  ...\\results\\figures

 REQUIREMENTS  (pip install ...)
   numpy pandas scipy matplotlib networkx powerlaw statsmodels scikit-learn
   python-igraph leidenalg

 DATA PROVENANCE
   Primary TRB data generated by Wang et al. (2017) Cancer Immunol Res 5(2):148-156;
   re-archived in TCRdb2 (host: West China Hospital), NCBI BioProject PRJNA301507.
   >> Confirm the accession, sample/patient counts and the subset labels against
      the primary record before trusting cohort-level numbers. <<

 License: MIT
================================================================================
"""

import os, sys, re, glob, warnings, itertools
import numpy as np
import pandas as pd
from scipy import stats, optimize
from scipy.spatial.distance import pdist, squareform
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")
try:
    from statsmodels.tools.sm_exceptions import ConvergenceWarning
    warnings.simplefilter("ignore", ConvergenceWarning)
except Exception:
    pass
RNG = np.random.default_rng(20240517)      # global seed for reproducibility
np.random.seed(20240517)

# =============================================================================
# 0. CONFIGURATION  (EDIT HERE)
# =============================================================================
DATA_DIR   = r"D:\PRJNA301507\data"        # <-- your data folder
META_FILE  = os.path.join(DATA_DIR, "sample_metadata.csv")
OUT_DIR    = r"D:\PRJNA301507\analysis_june_2026"
SUBSET_LEVELS = ["Treg", "CD4_Memory", "Other"]
SUBSET_COLORS = {"Treg": "#E64B35", "CD4_Memory": "#4DBBD5", "Other": "#00A087"}

QC_MIN_CLONOTYPES = 100
QC_MIN_READS      = 1000
PL_XMIN_FIXED     = 50          # fixed x_min for patient-level alpha (primary test)
PL_MIN_TAIL       = 20          # min clonotypes >= x_min to fit a patient
GOF_BOOT          = 0           # 0 = skip (very slow)
NET_PUBLIC_MIN_PATIENTS = 2     # 'strict public' = CDR3 shared by >= this many patients
N_BOOT_ICC        = 1000        # cluster-bootstrap reps for ICC CI
N_PERM            = 999         # PERMANOVA permutations
RAREFY_DRAWS      = 20          # rarefaction draws per repertoire (S4)

FIG_DIR = os.path.join(OUT_DIR, "figures")
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(FIG_DIR, exist_ok=True)

def log(msg): print(f"[TCR] {msg}", flush=True)

# =============================================================================
# 1. DATA LOADING
# =============================================================================
AA20 = set("ACDEFGHIKLMNPQRSTVWY")

COLUMN_ALIASES = {
    "cdr3aa": ["cdr3aa","aaseqcdr3","amino_acid","cdr3_amino_acid","cdr3","aaseq",
               "cdr3_aa","junction_aa","cdr3.aa","aaseq"],
    "v":      ["v","vgene","bestvgene","v_gene","vgenename","bestvhit","v_call","vgene_name","vregion"],
    "j":      ["j","jgene","bestjgene","j_gene","jgenename","bestjhit","j_call","jgene_name","jregion"],
    "count":  ["count","clonecount","templates","reads","productive_templates",
               "duplicate_count","clones","cloneCount","frequencycount","readcount"],
    "freq":   ["freq","frequency","productive_frequency","clonefraction","clonefreq","clone_fraction"],
    # optional metadata columns sometimes embedded in TCRdb2 exports
    "sample": ["sample","sample_id","runid","run","run_accession","srr","library","accession"],
    "patient":["patient","patient_id","subject","subject_id","donor","individual"],
    "subset": ["subset","celltype","cell_type","population","sort","phenotype"],
    "tissue": ["compartment","tissue","source","site","tissue_type"],
}

def _match_col(columns, aliases):
    low = {c.lower().strip(): c for c in columns}
    for a in aliases:
        if a in low:
            return low[a]
    for a in aliases:
        for lc, orig in low.items():
            if a in lc:
                return orig
    return None

def read_clonotype_table(path):
    """Read one clonotype file (CSV/TSV/txt). Returns DataFrame[cdr3aa,v,j,count]."""
    sep = "\t" if path.lower().endswith((".tsv", ".txt")) else None
    try:
        df = pd.read_csv(path, sep=sep, engine="python", compression="infer")
    except Exception as e:
        log(f"  ! could not read {os.path.basename(path)}: {e}")
        return None
    if df.shape[1] == 1:
        try: df = pd.read_csv(path, sep="\t", engine="python")
        except Exception: pass
    cols = list(df.columns)

    # filter for TRB chain if column exists
    chain_col = _match_col(cols, ["chain"])
    if chain_col is not None:
        df = df[df[chain_col].astype(str).str.upper().str.contains("TRB")]

    c_cdr3 = _match_col(cols, COLUMN_ALIASES["cdr3aa"])
    c_v    = _match_col(cols, COLUMN_ALIASES["v"])
    c_j    = _match_col(cols, COLUMN_ALIASES["j"])
    c_cnt  = _match_col(cols, COLUMN_ALIASES["count"])
    c_frq  = _match_col(cols, COLUMN_ALIASES["freq"])
    if c_cdr3 is None or c_v is None or c_j is None:
        raise ValueError(f"Missing CDR3/V/J columns in {os.path.basename(path)}. "
                         f"Columns present: {cols}")
    if c_cnt is None and c_frq is None:
        raise ValueError(f"No count or frequency column in {os.path.basename(path)}. "
                         f"Columns present: {cols}")
    out = pd.DataFrame({
        "cdr3aa": df[c_cdr3].astype(str),
        "v": df[c_v].astype(str),
        "j": df[c_j].astype(str),
    })
    if c_cnt is not None:
        out["count"] = pd.to_numeric(df[c_cnt], errors="coerce")
    else:
        fr = pd.to_numeric(df[c_frq], errors="coerce").fillna(0)
        out["count"] = np.maximum(1, np.round(fr / fr[fr > 0].min())).astype(float)
    return out

def standardise(df):
    """Apply QC/standardisation (Methods 2.2). Returns cleaned DataFrame or None."""
    if df is None or len(df) == 0:
        return None
    df = df.copy()
    df["v"] = df["v"].str.replace(r"\*.*$", "", regex=True)
    df["j"] = df["j"].str.replace(r"\*.*$", "", regex=True)
    df = df[df["cdr3aa"].notna() & (df["cdr3aa"] != "")]
    df = df[~df["cdr3aa"].str.contains(r"[*._]", regex=True, na=True)]
    df = df[df["cdr3aa"].apply(lambda s: len(s) >= 5 and len(s) <= 25 and set(s) <= AA20)]
    df = df[df["v"].str.startswith("TRBV") & df["j"].str.startswith("TRBJ")]
    df = df[pd.to_numeric(df["count"], errors="coerce").fillna(0) > 0]
    if len(df) == 0:
        return None
    df = df.groupby(["cdr3aa", "v", "j"], as_index=False)["count"].sum()
    df["freq"] = df["count"] / df["count"].sum()
    return df

def load_or_build_metadata(data_dir, meta_file):
    """Return DataFrame[file_name, sample_id, patient_id, subset, compartment]."""
    cand = meta_file
    if cand is None:
        for nm in ["sample_metadata.csv", "metadata.csv", "samples.csv", "meta.csv"]:
            p = os.path.join(data_dir, nm)
            if os.path.exists(p):
                cand = p; break
    if cand and os.path.exists(cand):
        m = pd.read_csv(cand)
        low = {c.lower(): c for c in m.columns}
        ren = {}
        for std, al in [("file_name", ["file_name","file","filename","path"]),
                        ("sample_id", COLUMN_ALIASES["sample"]),
                        ("patient_id", COLUMN_ALIASES["patient"]),
                        ("subset", COLUMN_ALIASES["subset"]),
                        ("compartment", COLUMN_ALIASES["tissue"])]:
            c = _match_col(m.columns, al)
            if c: ren[c] = std
        m = m.rename(columns=ren)
        log(f"Loaded metadata: {cand}  ({len(m)} rows)")
        return m

    files = []
    for ext in ("*.csv","*.tsv","*.txt","*.csv.gz","*.tsv.gz"):
        files += glob.glob(os.path.join(data_dir, "**", ext), recursive=True)
    files = sorted(set(files))
    files = [f for f in files if os.path.basename(f).lower() not in
             ("sample_metadata.csv","metadata.csv","samples.csv","meta.csv")]
    if not files:
        raise FileNotFoundError(f"No clonotype files found under {data_dir}")
    rows = []
    for f in files:
        base = os.path.splitext(os.path.basename(f))[0]
        rows.append({"file_name": os.path.relpath(f, data_dir),
                     "sample_id": base, "patient_id": np.nan,
                     "subset": np.nan, "compartment": np.nan})
    m = pd.DataFrame(rows)
    log(f"No metadata file found; built skeleton for {len(m)} files.")
    m.to_csv(os.path.join(OUT_DIR, "sample_metadata_TEMPLATE.csv"), index=False)
    return m

# =============================================================================
# 2-3. ALPHA DIVERSITY
# =============================================================================
def gini(x):
    x = np.sort(np.asarray(x, float)); n = len(x)
    if n == 0 or x.sum() == 0: return np.nan
    cum = np.cumsum(x)
    return (n + 1 - 2 * np.sum(cum) / cum[-1]) / n

def alpha_metrics(df):
    p = df["freq"].values; cnt = df["count"].values
    S = len(df); H = -np.sum(p * np.log(p))
    f1 = np.sum(cnt == 1); f2 = np.sum(cnt == 2)
    chao1 = S + (f1**2 / (2*f2) if f2 > 0 else f1*(f1-1)/2)
    o = np.sort(p)[::-1]
    pielou = H/np.log(S) if S > 1 else np.nan
    return dict(Shannon=H, invSimpson=1/np.sum(p**2), Gini=gini(cnt),
                Pielou=pielou, Clonality=(1-pielou) if S > 1 else np.nan,
                Hill0=S, Hill1=np.exp(H), Hill2=1/np.sum(p**2),
                Chao1=chao1, Sobs=S, Top10=float(np.sum(o[:max(1, int(0.10*S))])))

# =============================================================================
# 4. BETA DIVERSITY
# =============================================================================
def bray_curtis_matrix(M):
    return squareform(pdist(M, metric="braycurtis"))

def pcoa(D, k=2):
    n = D.shape[0]; D2 = D**2
    J = np.eye(n) - np.ones((n, n))/n
    B = -0.5 * J @ D2 @ J
    w, V = np.linalg.eigh(B)
    idx = np.argsort(w)[::-1]
    w, V = w[idx], V[:, idx]
    pos = w > 0
    coords = V[:, :k] * np.sqrt(np.abs(w[:k]))
    expl = w[:k] / w[pos].sum()
    return coords, expl

def permanova(D, labels, n_perm=999, seed=0):
    rng = np.random.default_rng(seed)
    labels = np.asarray(labels); n = len(labels); groups = np.unique(labels)
    D2 = D**2; SST = D2[np.triu_indices(n, 1)].sum() / n
    def ss_within(lab):
        s = 0.0
        for g in groups:
            idx = np.where(lab == g)[0]; ng = len(idx)
            if ng > 1:
                s += D2[np.ix_(idx, idx)][np.triu_indices(ng, 1)].sum() / ng
        return s
    SSW = ss_within(labels); SSA = SST - SSW
    a = len(groups)
    F = (SSA/(a-1)) / (SSW/(n-a))
    perm = np.empty(n_perm)
    for i in range(n_perm):
        lp = rng.permutation(labels)
        ssw = ss_within(lp); ssa = SST - ssw
        perm[i] = (ssa/(a-1)) / (ssw/(n-a))
    p = (np.sum(perm >= F) + 1) / (n_perm + 1)
    R2 = SSA / SST
    return dict(F=F, R2=R2, p=p, df1=a-1, df2=n-a)

def morisita_horn(x, y):
    keys = set(x) | set(y)
    xv = np.array([x.get(k, 0) for k in keys], float)
    yv = np.array([y.get(k, 0) for k in keys], float)
    px = xv/xv.sum(); py = yv/yv.sum()
    return 2*np.sum(px*py) / (np.sum(px**2) + np.sum(py**2))

# =============================================================================
# 5. POWER-LAW MODELLING
# =============================================================================
import powerlaw

def fit_powerlaw(counts, xmin=None, gof_boot=0):
    counts = np.asarray(counts, float); counts = counts[counts > 0]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fit = powerlaw.Fit(counts, discrete=True, xmin=xmin, verbose=False) \
              if xmin is not None else \
              powerlaw.Fit(counts, discrete=True, verbose=False)
    alpha = fit.power_law.alpha; xm = fit.power_law.xmin
    n_tail = int(np.sum(counts >= xm)); D = fit.power_law.D
    gof_p = np.nan
    if gof_boot and gof_boot > 0:
        gof_p = bootstrap_gof(counts, fit, n_boot=gof_boot)
    return dict(fit=fit, alpha=alpha, xmin=xm, n_tail=n_tail,
                tail_prop=n_tail/len(counts), D=D, gof_p=gof_p)

def bootstrap_gof(counts, fit, n_boot=200):
    counts = np.asarray(counts, float); counts = counts[counts > 0]
    xm = fit.power_law.xmin; alpha = fit.power_law.alpha; Demp = fit.power_law.D
    ntail = np.sum(counts >= xm); ntot = len(counts); ptail = ntail/ntot
    below = counts[counts < xm]
    ge = 0
    for _ in range(n_boot):
        n_t = RNG.binomial(ntot, ptail)
        synth_tail = fit.power_law.generate_random(n_t).astype(float) if n_t > 0 else np.array([])
        n_b = ntot - n_t
        synth_below = RNG.choice(below, size=n_b, replace=True) if (n_b > 0 and len(below) > 0) else np.array([])
        synth = np.concatenate([synth_tail, synth_below])
        if len(synth) < 10: continue
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                f2 = powerlaw.Fit(synth, discrete=True, verbose=False)
            if f2.power_law.D >= Demp: ge += 1
        except Exception:
            continue
    return ge / n_boot

def vuong_compare(counts):
    counts = np.asarray(counts, float); counts = counts[counts > 0]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fit = powerlaw.Fit(counts, discrete=True, verbose=False)
    out = {}
    for alt in ["lognormal", "exponential", "truncated_power_law"]:
        R, p = fit.distribution_compare("power_law", alt, normalized_ratio=True)
        out[alt] = (R, p)
    return out

# =============================================================================
# 7. MIXED MODEL + ICC
# =============================================================================
import statsmodels.formula.api as smf

def fit_icc(df, response="Shannon", group="patient_id", fixed="subset"):
    d = df[[response, group, fixed]].dropna().copy()
    d[fixed] = d[fixed].astype("category")
    md = smf.mixedlm(f"{response} ~ {fixed}", d, groups=d[group])
    mf = md.fit(reml=True, method="lbfgs")
    var_pat = float(mf.cov_re.iloc[0, 0]); var_res = float(mf.scale)
    icc = var_pat / (var_pat + var_res)
    return mf, icc, var_pat, var_res

def bootstrap_icc_ci(df, response="Shannon", group="patient_id", fixed="subset",
                     n_boot=1000, seed=20240517):
    rng = np.random.default_rng(seed)
    pats = df[group].dropna().unique(); iccs = []
    for _ in range(n_boot):
        samp = rng.choice(pats, size=len(pats), replace=True)
        parts = []
        for i, pid in enumerate(samp):
            sub = df[df[group] == pid].copy(); sub[group] = f"{pid}_{i}"
            parts.append(sub)
        bdf = pd.concat(parts, ignore_index=True)
        try:
            _, icc, _, _ = fit_icc(bdf, response, group, fixed)
            if np.isfinite(icc): iccs.append(icc)
        except Exception:
            continue
    if not iccs: return (np.nan, np.nan)
    return tuple(np.quantile(iccs, [0.025, 0.975]))

# =============================================================================
# helper effect sizes
# =============================================================================
def cohens_d(a, b):
    a = np.asarray(a, float); b = np.asarray(b, float)
    na, nb = len(a), len(b)
    sp = np.sqrt(((na-1)*np.var(a, ddof=1) + (nb-1)*np.var(b, ddof=1)) / (na+nb-2))
    return (np.mean(a)-np.mean(b))/sp if sp > 0 else np.nan

def rank_biserial(a, b):
    a = np.asarray(a, float); b = np.asarray(b, float)
    U, _ = stats.mannwhitneyu(a, b, alternative="two-sided")
    return 1 - 2*U/(len(a)*len(b))

def auc_score(a, b):
    from sklearn.metrics import roc_auc_score
    y = np.r_[np.ones(len(a)), np.zeros(len(b))]
    x = np.r_[a, b]
    auc = roc_auc_score(y, x)
    return max(auc, 1-auc)

def epsilon_squared_kw(H, n):
    return H/(n-1) if n > 1 else np.nan

# =============================================================================
# MAIN
# =============================================================================
def main():
    log(f"DATA_DIR = {DATA_DIR}")
    log(f"OUT_DIR  = {OUT_DIR}")

    # ---- 1. metadata + raw files ----
    meta = load_or_build_metadata(DATA_DIR, META_FILE)
    if "subset" not in meta or meta["subset"].isna().all():
        log("FATAL: subset labels (Treg/CD4_Memory/Other) are not available.")
        log("Fill results/sample_metadata_TEMPLATE.csv and set META_FILE, then re-run.")
        sys.exit(1)
    meta = meta[meta["subset"].isin(SUBSET_LEVELS)].reset_index(drop=True)

    # ---- 2. load + standardise ----
    log(f"Reading & standardising {len(meta)} samples ...")
    samples = {}
    for _, row in meta.iterrows():
        fp = os.path.join(DATA_DIR, str(row["file_name"]))
        if not os.path.exists(fp): fp = str(row["file_name"])
        samples[row["sample_id"]] = standardise(read_clonotype_table(fp))

    qc = []
    for _, r in meta.iterrows():
        s = samples.get(r["sample_id"])
        nclo = 0 if s is None else len(s)
        nrd = 0 if s is None else int(s["count"].sum())
        qc.append(dict(sample_id=r["sample_id"], patient_id=r["patient_id"],
                       subset=r["subset"], compartment=r.get("compartment", np.nan),
                       n_clono=nclo, n_reads=nrd,
                       pass_qc=(nclo >= QC_MIN_CLONOTYPES and nrd >= QC_MIN_READS)))
    qc = pd.DataFrame(qc)
    qc.to_csv(os.path.join(OUT_DIR, "TableS_sample_sheet_QC.csv"), index=False)
    keep = qc.loc[qc["pass_qc"], "sample_id"].tolist()
    samples = {k: v for k, v in samples.items() if k in keep}
    meta_qc = meta[meta["sample_id"].isin(keep)].reset_index(drop=True)
    log(f"QC: {len(keep)}/{len(qc)} samples pass; "
        f"{meta_qc['patient_id'].nunique()} patients.")

    def pool_subset(sub):
        ids = meta_qc.loc[meta_qc["subset"] == sub, "sample_id"]
        big = pd.concat([samples[i] for i in ids if samples.get(i) is not None],
                        ignore_index=True)
        big = big.groupby(["cdr3aa", "v", "j"], as_index=False)["count"].sum()
        return big.sort_values("count", ascending=False)
    pools = {s: pool_subset(s) for s in SUBSET_LEVELS}

    # ---- 3. alpha diversity ----
    rows = []
    for _, r in meta_qc.iterrows():
        s = samples.get(r["sample_id"])
        if s is None: continue
        m = alpha_metrics(s); m.update(sample_id=r["sample_id"],
            patient_id=r["patient_id"], subset=r["subset"])
        rows.append(m)
    adt = pd.DataFrame(rows)
    adt.to_csv(os.path.join(OUT_DIR, "Table2_alpha_diversity.csv"), index=False)
    summ = adt.groupby("subset")[["Shannon","invSimpson","Gini","Pielou",
        "Clonality","Top10","Sobs","Chao1"]].agg(["mean","std"])
    summ.to_csv(os.path.join(OUT_DIR, "Table2_alpha_summary.csv"))
    log("Alpha diversity done.")

    # ---- 4. beta diversity ----
    all_clones = pd.concat(samples.values(), ignore_index=True)
    all_clones["clone"] = all_clones["cdr3aa"]+"|"+all_clones["v"]+"|"+all_clones["j"]
    top = (all_clones.groupby("clone")["count"].sum()
           .sort_values(ascending=False).head(5000).index.tolist())
    sid = list(samples.keys())
    M = np.zeros((len(sid), len(top)))
    cidx = {c: i for i, c in enumerate(top)}
    for r, s_id in enumerate(sid):
        s = samples[s_id].copy()
        s["clone"] = s["cdr3aa"]+"|"+s["v"]+"|"+s["j"]
        s = s[s["clone"].isin(cidx)]
        for cl, cn in zip(s["clone"], s["count"]):
            M[r, cidx[cl]] = cn
    keepr = M.sum(1) > 0
    M = M[keepr]; sid = [s for s, k in zip(sid, keepr) if k]
    lab = meta_qc.set_index("sample_id").loc[sid, "subset"].values
    D = bray_curtis_matrix(M)
    coords, expl = pcoa(D, 2)
    perm = permanova(D, lab, n_perm=N_PERM, seed=1)
    log(f"PERMANOVA: R2={perm['R2']:.3f}, F={perm['F']:.3f}, p={perm['p']:.3f}")
    pool_vec = {s: dict(zip(pools[s]["cdr3aa"]+"|"+pools[s]["v"]+"|"+pools[s]["j"],
                            pools[s]["count"])) for s in SUBSET_LEVELS}
    mh = pd.DataFrame([
        ("Treg vs CD4_Memory", morisita_horn(pool_vec["Treg"], pool_vec["CD4_Memory"])),
        ("Treg vs Other",      morisita_horn(pool_vec["Treg"], pool_vec["Other"])),
        ("CD4_Memory vs Other",morisita_horn(pool_vec["CD4_Memory"], pool_vec["Other"])),
    ], columns=["pair", "C_MH"])
    mh.to_csv(os.path.join(OUT_DIR, "Table_morisita_horn.csv"), index=False)

    # ---- 5. power-law (pooled, descriptive) ----
    pl_rows = []
    for s in SUBSET_LEVELS:
        f = fit_powerlaw(pools[s]["count"].values, gof_boot=GOF_BOOT)
        pl_rows.append(dict(subset=s, alpha=round(f["alpha"],3), xmin=f["xmin"],
            n_tail=f["n_tail"], tail_pct=round(100*f["tail_prop"],2),
            KS_D=round(f["D"],4), gof_p=round(f["gof_p"],3) if np.isfinite(f["gof_p"]) else np.nan))
    pd.DataFrame(pl_rows).to_csv(os.path.join(OUT_DIR, "Table3_powerlaw_pooled.csv"), index=False)
    log("Pooled power-law done: " + ", ".join(f"{r['subset']} a={r['alpha']}" for r in pl_rows))

    # Vuong-style model comparison
    vrows = []
    for s in SUBSET_LEVELS:
        cmp = vuong_compare(pools[s]["count"].values)
        vrows.append(dict(subset=s,
            vs_lognormal_R=round(cmp["lognormal"][0],3),  vs_lognormal_p=round(cmp["lognormal"][1],3),
            vs_exponential_R=round(cmp["exponential"][0],3), vs_exponential_p=round(cmp["exponential"][1],3),
            vs_truncPL_R=round(cmp["truncated_power_law"][0],3), vs_truncPL_p=round(cmp["truncated_power_law"][1],3)))
    pd.DataFrame(vrows).to_csv(os.path.join(OUT_DIR, "Table_model_comparison.csv"), index=False)

    # patient-level alpha (PRIMARY tested comparison)
    def patient_alpha(xmin=PL_XMIN_FIXED):
        res = []
        for sub in SUBSET_LEVELS:
            for pid in meta_qc.loc[meta_qc["subset"]==sub, "patient_id"].unique():
                ids = meta_qc[(meta_qc["subset"]==sub)&(meta_qc["patient_id"]==pid)]["sample_id"]
                cc = pd.concat([samples[i] for i in ids if samples.get(i) is not None],
                               ignore_index=True)
                if len(cc)==0: continue
                cc = cc.groupby(["cdr3aa","v","j"], as_index=False)["count"].sum()["count"].values
                if np.sum(cc >= xmin) < PL_MIN_TAIL: continue
                try:
                    f = fit_powerlaw(cc, xmin=xmin, gof_boot=0)
                    if np.isfinite(f["alpha"]):
                        res.append(dict(patient_id=pid, subset=sub, alpha=f["alpha"]))
                except Exception: continue
        return pd.DataFrame(res)
    pa = patient_alpha()
    pa.to_csv(os.path.join(OUT_DIR, "Table_patient_level_alpha.csv"), index=False)
    if len(pa):
        med = pa.groupby("subset")["alpha"].median()
        tr = pa[pa.subset=="Treg"]["alpha"].values; me = pa[pa.subset=="CD4_Memory"]["alpha"].values
        ot = pa[pa.subset=="Other"]["alpha"].values
        def safe_mw(a,b): return stats.mannwhitneyu(a,b)[1] if len(a)>2 and len(b)>2 else np.nan
        log(f"Patient-level alpha medians: " + ", ".join(f"{k}={v:.2f}" for k,v in med.items()))
        log(f"  Treg vs CD4_Memory p={safe_mw(tr,me):.3f} r={rank_biserial(tr,me):.2f}; "
            f"Treg vs Other p={safe_mw(tr,ot):.3f} r={rank_biserial(tr,ot):.2f}")
        pr = pd.merge(pa[pa.subset=="Treg"][["patient_id","alpha"]].rename(columns={"alpha":"treg"}),
                      pa[pa.subset=="CD4_Memory"][["patient_id","alpha"]].rename(columns={"alpha":"mem"}),
                      on="patient_id")
        if len(pr): log(f"  Treg<CD4_Memory in {int((pr.treg<pr.mem).sum())}/{len(pr)} patients")

    # x_min sensitivity
    xs_rows = []
    for xm in (25,50,75,100):
        d = patient_alpha(xm)
        if len(d):
            xs_rows.append(dict(xmin=xm, **{k: round(d[d.subset==k]["alpha"].median(),3) for k in SUBSET_LEVELS}))
    pd.DataFrame(xs_rows).to_csv(os.path.join(OUT_DIR, "TableS1_xmin_sensitivity.csv"), index=False)

    # ---- 6. network ----
    import igraph as ig
    pc = {}
    for pid in meta_qc["patient_id"].unique():
        ids = meta_qc[meta_qc["patient_id"]==pid]["sample_id"]
        cc = pd.concat([samples[i] for i in ids if samples.get(i) is not None], ignore_index=True)
        pc[pid] = set(cc["cdr3aa"].unique())
    n_total = len(pc)
    allc = pd.Series([c for s in pc.values() for c in s]).value_counts()
    public = set(allc[allc >= NET_PUBLIC_MIN_PATIENTS].index)
    pub = {p: (cset & public) for p, cset in pc.items()}
    has_treg = {p: not meta_qc[(meta_qc.patient_id==p)&(meta_qc.subset=="Treg")].empty for p in pub}
    pub = {p: s for p, s in pub.items() if len(s) > 0 and has_treg[p]}
    pids = list(pub.keys())
    log(f"Network: {n_total} patients -> {len(pids)} retained "
        f"({n_total-len(pids)} excluded as isolated/no-Treg).")
    N = len(pids); W = np.zeros((N, N))
    for i in range(N):
        for j in range(i+1, N):
            a, b = pub[pids[i]], pub[pids[j]]
            u = len(a | b); W[i,j] = W[j,i] = (len(a & b)/u if u else 0)
    edges = [(i,j,W[i,j]) for i in range(N) for j in range(i+1,N) if W[i,j] > 0]
    g = ig.Graph(n=N); g.add_edges([(e[0],e[1]) for e in edges])
    g.es["weight"] = [e[2] for e in edges]; g.vs["name"] = [str(p) for p in pids]
    net = dict(nodes=N, edges=g.ecount(), density=g.density(),
               transitivity=g.transitivity_undirected(mode="zero"),
               mean_degree=np.mean(g.degree()),
               diameter=(g.diameter(weights=None) if g.ecount() else np.nan))
    louv = g.community_multilevel(weights="weight")
    net["communities"] = len(louv); net["modularity"] = g.modularity(louv, weights="weight")
    pd.DataFrame([net]).to_csv(os.path.join(OUT_DIR, "Table4_network_metrics.csv"), index=False)
    log(f"Network: density={net['density']:.3f}, communities={net['communities']}, "
        f"Q={net['modularity']:.3f}")

    def treg_dom(pid):
        ids = meta_qc[(meta_qc.subset=="Treg")&(meta_qc.patient_id==pid)]["sample_id"]
        cc = pd.concat([samples[i] for i in ids if samples.get(i) is not None], ignore_index=True)
        if len(cc)==0: return np.nan
        cc = cc.groupby(["cdr3aa","v","j"], as_index=False)["count"].sum()
        return cc["count"].max()/cc["count"].sum()
    comm = pd.DataFrame(dict(patient_id=pids,
            community=list(louv.membership), degree=g.degree(),
            centrality=[d/(N-1) if N>1 else 0 for d in g.degree()]))
    comm["treg_dom"] = comm["patient_id"].map(treg_dom)
    cc_dat = comm.dropna(subset=["treg_dom"])
    if cc_dat["community"].nunique() > 1:
        grps = [v["treg_dom"].values for _, v in cc_dat.groupby("community")]
        H, pkw = stats.kruskal(*grps)
        eps2 = epsilon_squared_kw(H, len(cc_dat))
        log(f"Kruskal-Wallis treg_dom~community: H={H:.2f}, p={pkw:.5f}, eps^2={eps2:.3f}")
    comm.to_csv(os.path.join(OUT_DIR, "Table_network_communities.csv"), index=False)

    # ---- 7. mixed model + ICC ----
    try:
        mf, icc, vp, vr = fit_icc(adt, "Shannon", "patient_id", "subset")
        lo, hi = bootstrap_icc_ci(adt, n_boot=min(N_BOOT_ICC, 500))
        log(f"ICC(Shannon)={icc:.3f}  (cluster-bootstrap 95% CI {lo:.3f}-{hi:.3f})")
        pd.DataFrame([dict(metric="Shannon", ICC=icc, CI_low=lo, CI_high=hi,
                           var_patient=vp, var_resid=vr)]).to_csv(
            os.path.join(OUT_DIR, "Table_ICC.csv"), index=False)
        d_d = cohens_d(adt[adt.subset=="Treg"]["Shannon"], adt[adt.subset=="CD4_Memory"]["Shannon"])
        log(f"Cohen's d (Treg vs CD4_Memory, Shannon) = {d_d:.3f}")
    except Exception as e:
        log(f"Mixed model failed: {e}")

    # ICC across metrics
    icc_rows = []
    for m in ["Shannon","invSimpson","Gini","Pielou","Clonality","Hill1"]:
        try:
            _, ic, _, _ = fit_icc(adt, m, "patient_id", "subset"); icc_rows.append((m, ic))
        except Exception: pass
    pd.DataFrame(icc_rows, columns=["metric","ICC"]).to_csv(
        os.path.join(OUT_DIR, "Table_ICC_all_metrics.csv"), index=False)

    # ---- 8. centrality vs alpha ----
    if len(pa):
        ca = pd.merge(comm[["patient_id","centrality"]],
                      pa[pa.subset=="Treg"][["patient_id","alpha"]], on="patient_id").dropna()
        if len(ca) > 3 and ca["centrality"].nunique() > 1 and ca["alpha"].nunique() > 1:
            rho, pval = stats.spearmanr(ca["centrality"], ca["alpha"])
            log(f"Spearman centrality vs Treg alpha: rho={rho:.3f}, p={pval:.3f}, n={len(ca)}")
            pd.DataFrame([dict(rho=rho, p=pval, n=len(ca))]).to_csv(
                os.path.join(OUT_DIR, "Table_centrality_vs_alpha.csv"), index=False)
        else:
            log(f"Spearman centrality vs Treg alpha: insufficient variance/overlap (n={len(ca)}) - skipped")

    # ---- 9. PERMANOVA power ----
    R2 = perm["R2"]; f2 = R2/(1-R2); v = len(sid)-len(SUBSET_LEVELS)
    try:
        from statsmodels.stats.power import FTestPower
        power = FTestPower().power(effect_size=np.sqrt(f2), df_num=len(SUBSET_LEVELS)-1,
                                   df_denom=v, alpha=0.05)
        log(f"PERMANOVA power approx: R2={R2:.3f}, f2={f2:.3f}, power~{power:.2f}")
    except Exception as e:
        log(f"power calc skipped: {e}")

    # =========================================================================
    # 10. STRENGTHENING ANALYSES
    # =========================================================================
    log("=== strengthening analyses ===")

    # S1 metric benchmark (patient-level, Treg vs CD4_Memory)
    def patient_subset_metrics():
        rows = []
        for sub in SUBSET_LEVELS:
            for pid in meta_qc.loc[meta_qc.subset==sub, "patient_id"].unique():
                ids = meta_qc[(meta_qc.subset==sub)&(meta_qc.patient_id==pid)]["sample_id"]
                cc = pd.concat([samples[i] for i in ids if samples.get(i) is not None], ignore_index=True)
                if len(cc)==0: continue
                cc = cc.groupby(["cdr3aa","v","j"], as_index=False)["count"].sum()
                cc["freq"] = cc["count"]/cc["count"].sum()
                m = alpha_metrics(cc); m.update(patient_id=pid, subset=sub); rows.append(m)
        return pd.DataFrame(rows)
    psm = patient_subset_metrics()
    if len(pa): psm = psm.merge(pa, on=["patient_id","subset"], how="left")
    bench = []
    for m in ["Shannon","invSimpson","Gini","Pielou","Clonality","Top10","Hill1","Chao1","alpha"]:
        if m not in psm.columns: continue
        a = psm[psm.subset=="Treg"][m].dropna().values
        b = psm[psm.subset=="CD4_Memory"][m].dropna().values
        if len(a)<3 or len(b)<3: continue
        bench.append(dict(metric=m, cohens_d=round(abs(cohens_d(a,b)),3),
            AUC=round(auc_score(a,b),3), p=round(stats.mannwhitneyu(a,b)[1],4),
            n_Treg=len(a), n_Mem=len(b)))
    bench = pd.DataFrame(bench).sort_values("cohens_d", ascending=False)
    bench.to_csv(os.path.join(OUT_DIR, "TableS_metric_benchmark.csv"), index=False)
    log("S1 benchmark top metric: " + (bench.iloc[0]["metric"] if len(bench) else "n/a"))

    # S2 truncated power-law
    s2 = []
    for s in SUBSET_LEVELS:
        cmp = vuong_compare(pools[s]["count"].values)
        R, p = cmp["truncated_power_law"]
        pref = ("indistinguishable" if p>0.05 else ("pure PL" if R>0 else "truncated PL"))
        s2.append(dict(subset=s, PL_vs_truncPL_R=round(R,3), p=round(p,3), preferred=pref))
    pd.DataFrame(s2).to_csv(os.path.join(OUT_DIR, "TableS_truncated_powerlaw.csv"), index=False)

    # S3 community robustness
    rob = []
    algos = {"Louvain": louv}
    if hasattr(g, 'ecount') and g.ecount():
        try: algos["Leiden"] = g.community_leiden(objective_function="modularity", weights="weight")
        except Exception: pass
        try: algos["Walktrap"] = g.community_walktrap(weights="weight").as_clustering()
        except Exception: pass
        try: algos["Infomap"] = g.community_infomap(edge_weights="weight")
        except Exception: pass
    def ari(a, b):
        from sklearn.metrics import adjusted_rand_score
        return adjusted_rand_score(a, b)
    for nm, cl in algos.items():
        if cl is None: continue
        rob.append(dict(algorithm=nm, n_communities=len(cl),
            modularity=round(g.modularity(cl, weights="weight"),3),
            ARI_vs_Louvain=round(ari(louv.membership, cl.membership),3)))
    pd.DataFrame(rob).to_csv(os.path.join(OUT_DIR, "TableS_community_robustness.csv"), index=False)

    # S4 rarefaction-to-equal-depth alpha
    if len(qc):
        depth = int(np.quantile(qc.loc[qc.pass_qc, "n_reads"], 0.10))
        def rarefy(cnt, d):
            cnt = np.asarray(cnt, float)
            if cnt.sum() <= d: return cnt
            idx = RNG.choice(len(cnt), size=d, replace=True, p=cnt/cnt.sum())
            return np.bincount(idx, minlength=len(cnt)).astype(float)
        rrows = []
        for sub in SUBSET_LEVELS:
            for pid in meta_qc.loc[meta_qc.subset==sub, "patient_id"].unique():
                ids = meta_qc[(meta_qc.subset==sub)&(meta_qc.patient_id==pid)]["sample_id"]
                cc = pd.concat([samples[i] for i in ids if samples.get(i) is not None], ignore_index=True)
                if len(cc)==0: continue
                cc = cc.groupby(["cdr3aa","v","j"], as_index=False)["count"].sum()["count"].values
                if cc.sum() < depth: continue
                al = []
                for _ in range(RAREFY_DRAWS):
                    rc = rarefy(cc, depth); rc = rc[rc>0]
                    if np.sum(rc>=PL_XMIN_FIXED) < PL_MIN_TAIL: continue
                    try:
                        f = fit_powerlaw(rc, xmin=PL_XMIN_FIXED, gof_boot=0)
                        if np.isfinite(f["alpha"]): al.append(f["alpha"])
                    except Exception: pass
                if al: rrows.append(dict(patient_id=pid, subset=sub, alpha_rarefied=np.mean(al)))
        rdf = pd.DataFrame(rrows)
        rdf.to_csv(os.path.join(OUT_DIR, "TableS_rarefied_alpha.csv"), index=False)
        if len(rdf):
            log("S4 rarefied alpha medians: " +
                ", ".join(f"{k}={v:.2f}" for k,v in rdf.groupby('subset')['alpha_rarefied'].median().items()))

    # =========================================================================
    # 11. FIGURES
    # =========================================================================
    def save(fig, name):
        fig.tight_layout(); fig.savefig(os.path.join(FIG_DIR, name), dpi=300); plt.close(fig)

    # Fig1 alpha boxplots
    fig, ax = plt.subplots(figsize=(6,4))
    data = [adt[adt.subset==s]["Shannon"].dropna() for s in SUBSET_LEVELS]
    bp = ax.boxplot(data, labels=SUBSET_LEVELS, patch_artist=True)
    for patch, s in zip(bp["boxes"], SUBSET_LEVELS): patch.set_facecolor(SUBSET_COLORS[s])
    ax.set_ylabel("Shannon entropy H'"); ax.set_title("Alpha diversity")
    save(fig, "Fig1_alpha_diversity.png")

    # Fig2 PCoA
    fig, ax = plt.subplots(figsize=(6.5,5))
    for s in SUBSET_LEVELS:
        m = lab == s
        ax.scatter(coords[m,0], coords[m,1], label=s, c=SUBSET_COLORS[s], alpha=.8)
    ax.set_xlabel(f"PCo1 ({100*expl[0]:.1f}%)"); ax.set_ylabel(f"PCo2 ({100*expl[1]:.1f}%)")
    ax.set_title(f"Bray-Curtis PCoA (PERMANOVA R2={perm['R2']:.3f}, p={perm['p']:.3f})"); ax.legend()
    save(fig, "Fig2_pcoa.png")

    # Fig4 power-law rank-frequency
    fig, ax = plt.subplots(figsize=(6.5,5))
    for s in SUBSET_LEVELS:
        c = np.sort(pools[s]["count"].values)[::-1]
        ax.loglog(np.arange(1,len(c)+1), c, label=s, color=SUBSET_COLORS[s])
    ax.set_xlabel("Clone rank (log)"); ax.set_ylabel("Clone count (log)")
    ax.set_title("Power-law rank-frequency"); ax.legend()
    save(fig, "Fig4_powerlaw_rankfreq.png")

    # Fig5 patient-level alpha
    if len(pa):
        fig, ax = plt.subplots(figsize=(6,4))
        data = [pa[pa.subset==s]["alpha"].dropna() for s in SUBSET_LEVELS]
        bp = ax.boxplot(data, labels=SUBSET_LEVELS, patch_artist=True)
        for patch, s in zip(bp["boxes"], SUBSET_LEVELS): patch.set_facecolor(SUBSET_COLORS[s])
        ax.set_ylabel("Power-law exponent alpha"); ax.set_title("Patient-level alpha (primary test)")
        save(fig, "Fig5_alpha_by_subset.png")

    # FigS1 benchmark
    if len(bench):
        fig, ax = plt.subplots(figsize=(6,4))
        b = bench.sort_values("cohens_d")
        ax.barh(b["metric"], b["cohens_d"],
                color=["#E64B35" if m=="alpha" else "grey" for m in b["metric"]])
        ax.set_xlabel("Cohen's d (Treg vs CD4_Memory)"); ax.set_title("Metric discrimination")
        save(fig, "FigS_metric_benchmark.png")

    # Fig7 network
    if g.ecount():
        fig, ax = plt.subplots(figsize=(6,6))
        layout = g.layout_fruchterman_reingold()
        xy = np.array(layout.coords)
        for e in g.es:
            x0,y0 = xy[e.source]; x1,y1 = xy[e.target]
            ax.plot([x0,x1],[y0,y1], color="grey", lw=0.3*e["weight"]+0.1, alpha=0.3, zorder=1)
        cmap = plt.cm.tab10
        ax.scatter(xy[:,0], xy[:,1], c=[cmap(m % 10) for m in louv.membership],
                   s=30+8*np.array(g.degree()), zorder=2, edgecolors="k", linewidths=0.3)
        ax.set_title(f"Inter-patient sharing network (density={net['density']:.3f})")
        ax.axis("off"); save(fig, "Fig7_network.png")

    log("DONE. Tables -> %s ; figures -> %s" % (OUT_DIR, FIG_DIR))

if __name__ == "__main__":
    main()
